### ISSUE TITLE
License Question - Platforms

### ISSUE THREAD

**Issue by GregSlazinski** [NVIDIAGameWorks/PhysX-3.4#52]
Hi,

I've sent an email few days ago to gameworkslicensing@nvidia.com but didn't get a reply.

I'd like to clarify the free platforms, "Windows, Linux, OSX, iOS and Android platforms (the “Authorized Platforms”)", however Windows is such a broad platform right now. So I'd like to ask specifically, can PhysX be used for free on the following:

(UWP = Universal Windows Platform)

1) Windows UWP 32/64 - for Desktop
2) Windows UWP Arm - for Phone
3) Windows UWP 32/64 - for Xbox - from what I've heard Xbox now runs Windows OS and can run Windows UWP based apps, but I've never tried it.
4) What about "Emscripten - Web"? Web browsers are mostly used on Windows Linux OSX iOS Android, and those platforms are supposedly free to use, so does that make Emscripten platform free as well?

Thank you,

Greg

**Comment by amoravanszky** [comment]
Our desire would be to have all our platforms under BSD-3.  The only reason we cannot realize this for consoles because standard contractual obligation with console makers around nondisclosure of console SDKs prevent it.   But you are welcome to use the code we make available here on any platform that you can successfully build it on, including with your own changes to port to consoles -- we don't intend to make any restrictions.  Of course you are also welcome to reach out to us about closed platform source too, and we will share the console ports with you if we are able to verify with Sony/Microsoft/Nintendo that you are a license developer for their respective platforms.
